security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: phone

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        web:
            pattern: ^/(?!api)
            stateless: false
            provider: app_user_provider
            
            oauth:
                resource_owners:
                    google: "/connect/check-google"
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                    service: App\Service\OAuthUserProvider
                default_target_path: /profile
            
            logout:
                path: /logout
                target: /login?logout=success
        
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JwtAuthenticator
            entry_point: App\Security\JwtAuthenticator

    access_control:
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs.json, roles: PUBLIC_ACCESS }
        - { path: ^/api/contexts, roles: PUBLIC_ACCESS }
        - { path: ^/api/houses, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, methods: [POST], roles: PUBLIC_ACCESS }
        - { path: ^/api/houses/available, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/connect, role: PUBLIC_ACCESS }
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/$, role: PUBLIC_ACCESS }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }