services:
  database:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: app
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - .:/var/www
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www

volumes:
  database_data:

networks:
  default:
    driver: bridge
